import { fetchFromGrafanaProxy, PROXY_DEVOPS_URL } from "./FetchService";

// --- Services ---

/**
 * Closes a connection using a command.
 */
export const closeConnectionService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/command`, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain' },
        data: 'connectivity.commands:closeConnection'
    });
}

/**
 * Creates or updates a connection with a specific ID.
 */
export const createConnectionWithIdService = async (id: string, data: any) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}`, {
        method: 'PUT',
        data: data
    });
}

/**
 * Creates a new connection (ID generated by server).
 */
export const createConnectionWithoutIdService = async (data: any) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections`, {
        method: 'POST',
        data: data
    });
}

/**
 * Deletes a connection by its ID.
 */
export const deleteConnectionByIdService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}`, {
        method: 'DELETE'
    });
}

/**
 * Gets all connection IDs.
 */
export const getAllConnectionIdsService = async () => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections`, {
        method: 'GET'
    });
}

/**
 * Gets a specific connection by its ID.
 */
export const getConnectionByIdService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}`, {
        method: 'GET'
    });
}

/**
 * Gets logs for a specific connection.
 */
export const getLogsByConnectionIdService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/logs`, {
        method: 'GET'
    });
}

/**
 * Enables logs for a specific connection.
 */
export const enableConnectionLogsService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/command`, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain' },
        data: 'connectivity.commands:enableConnectionLogs'
    });
}

/**
 * Gets metrics for a specific connection.
 */
export const getMetricsByConnectionIdService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/metrics`, {
        method: 'GET'
    });
}

/**
 * Gets the status of a specific connection.
 */
export const getStatusByConnectionIdService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/status`, {
        method: 'GET'
    });
}

/**
 * Opens a connection using a command.
 */
export const openConnectionService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/command`, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain' },
        data: 'connectivity.commands:openConnection'
    });
}

/**
 * Resets/Refreshes logs for a connection.
 */
export const refreshLogsByConnectionIdService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/command`, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain' },
        data: 'connectivity.commands:resetConnectionLogs'
    });
}

/**
 * Resets/Refreshes metrics for a connection.
 */
export const refreshMetricsByConnectionIdService = async (id: string) => {
    return await fetchFromGrafanaProxy(`${PROXY_DEVOPS_URL}/connections/${id}/command`, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain' },
        data: 'connectivity.commands:resetConnectionMetrics'
    });
}
